### ISSUE TITLE
Translations dissapeared

### ISSUE THREAD

**Issue by maqlec** [Magento2Translations/language_pl_pl#1]
Hi,
Today build deleted over 7000 translations. Please check it out.

**Comment by MrGekko** [comment]
This is quite a disturbing issue. 
I am glad that after a re compile all branches are back up to the 7000 line.
So after a composer update all should be back to normal for you.

For now I will regard the issue as a freak accident (although it only occurred in some of the translations)
Please report to me again if the issue is back. And sorry for the inconvenience.
